### PR TITLE
fix: remove library module name in vue wrapper build

### PR DESCRIPTION
**Pull request by jwlee1108**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

This PR is to fix vue-chart build script. When `@toast-ui/vue-chart` is imported in the version before the change, the chart is contained in an `toastui` object.

* When we write code below
  ```js 
  import tui from '@toast-ui/vue-chart;
  console.log(tui);
  ```
  image

Related to [#686](https://github.com/nhn/tui.chart/issues/686)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Review by dongsik-yoo — APPROVED** [review]
리뷰 완료합니다. 수고하셨습니다.

**Review by lja1018 — APPROVED** [review]
리뷰완료합니다.

**Review by adhrinae — APPROVED** [review]
리뷰 완료합니다.

**Review by js87zz — APPROVED** [review]
늦었지만 리뷰 완료합니다~!

**Pull request merged**
