### PR TITLE
Security fix for Cross-Site Scripting Vulnerability in the legend fields

### PR DESCRIPTION
**Pull request by arjunshibu**
Fix for Cross-site Scripting vulnerability

Resolves the bug  mentioned in #601 completely without affecting any functionality

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

Fully described here https://github.com/418sec/tui.chart/pull/2

Please do not merge this commit directly as I said here https://github.com/nhn/tui.chart/issues/601#issuecomment-786454161
Once you are happy with the fix, please comment here https://github.com/418sec/tui.chart/pull/2 🚀. Thanks in advance 😄 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by jung-han** [comment]
@arjunshibu 
Sorry for late. I left a review on that repo! I would be grateful if you check it out.

**Comment by arjunshibu** [comment]
@jung-han sure. I'll update it ASAP

**Comment by arjunshibu** [comment]
@jung-han I've modified the types and added trailing commas. But as you can see one type check is still failing. When I give type as `string | DocumentFragment` in `finalizeHtml()`, this error goes but another one come from line 150 and 151. A little help about the type from your side will be very useful.

https://github.com/arjunshibu/tui.chart/blob/a7a212124dae136a84034648fc90fe9bfadfbd03/apps/chart/src/component/tooltip.ts#L147-L156

**Comment by jung-han** [comment]
@arjunshibu 
This is the new sanitizer with the type added. I brought a link in case it could be a reference. If you see this part and it is still difficult to confirm, please let me know. 🌝

* https://github.com/nhn/tui.editor/blob/next/apps/editor/src/sanitizer/htmlSanitizer.ts

**Comment by arjunshibu** [comment]
@jung-han thank you so much. I'll work on this tomorrow 😄

**Comment by arjunshibu** [comment]
@jung-han sorry for the delay. All errors are now resolved 😄 Thanks again for the type suggestion. If you are okay with this commit, please comment `@huntr-helper - LGTM` on https://github.com/418sec/tui.chart/pull/2

**Comment by jung-han** [comment]
@arjunshibu 
I'll let you know after testing tomorrow! Thanks for the fix!

**Comment by arjunshibu** [comment]
Similar issue exists on https://github.com/nhn/tui.calendar in the event fields. Can I fix this?

**Review by jung-han — APPROVED** [review]

**Comment by arjunshibu** [comment]
@jung-han can you please comment the message bot wants to hear on the 418sec repo, so that I can earn a reward for fixing this vulnerability 😊

**Comment by jung-han** [comment]
@arjunshibu 

`@ huntr-helper-LGTM` right?

**Comment by arjunshibu** [comment]
@jung-han `@huntr-helper - LGTM` 🙂

**Pull request merged**
